name: Publish
run-name: ${{ gitea.actor }} Actions 🚀
on:
  push:
    branches:
      # - 'main'
      - 'release/**'

jobs:
  Publish-Weapp-Actions:
    runs-on: macos-arm64
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."
      - run: echo "🎉 检查当前目录 ${{ env.GITHUB_WORKSPACE }} ."
      - run: node -v
      - run: npx gitea-cli origin pull /Users/wmc/work/_temp/gitea-ci/test-repo -r "https://github.com/WumaCoder/gitea-repo"
      - run: cd /Users/wmc/work/_temp/gitea-ci/test-repo && npx semantic-release && git push
      - run: echo "🍏 This job's status is ${{ job.status }}."